[package]
name = "fancy_mumble"
version = "0.2.2"
description = "Fancy Mumble"
authors = ["SetZero"]
license = "MIT"
repository = ""
default-run = "fancy_mumble"
edition = "2024"
rust-version = "1.86"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.2.0", features = [] }
prost-build = "0.13.5"
reqwest = { version = "0.12.15", features = ["cookies"] }
sha2 = "0.10.9"
tokio = { version = "1.44.2", features = ["full"] }
patch = "0.7.0"

[dependencies]
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
tauri = { version = "^2.5.1", features = [] }
futures = "0.3.31"
tokio = { version = "1", features = ["full"] }
tokio-native-tls = "0.3.1"
prost = "0.13.5"
byteorder = "1.4.3"
async-trait = "0.1.88"
tracing = "0.1.41"
tracing-subscriber = {version = "0.3.19", features = ["env-filter"] }
base64 = "0.22.1"
os_info = "3.10.0"
rodio = "0.20.1"
directories = "6.0.0"
num-traits = "0.2.19"
brotli = "8.0.0"
webbrowser = "1.0.4"
reqwest = "0.12"
scraper = "0.23.1"
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" , version = "2.0.0" }
tauri-plugin-store = { version = "2" }
symphonia = "0.5.3"
mime_guess = "2.0.5"
uuid = "1.16.0"
tauri-plugin-dialog = "2"
audiopus_sys = { git = "https://github.com/SetZero/audiopus_sys", branch = "master" }
image = "0.25.6"
opus =  "0.3.0"
tauri-plugin-os = "2.2.1"

[dev-dependencies]
tempfile = "3.19.1"
mockall = "0.13.1"
tokio-test = "0.4.2"
xshell = "0.2.7"

[target.'cfg(any(target_os = "windows", target_os = "linux", target_os = "macos"))'.dependencies]

openssl = "0.10.72"

[target.'cfg(target_os = "android")'.dependencies]
oboe = { version = "0.6.1", features = [ "java-interface", "shared-stdcxx" ] } # Android
openssl = { version = "0.10", features = ["vendored"] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
debug = 1

[profile.optimized]
inherits = "release"
lto = true
codegen-units = 1

#[rust]
#debuginfo-level = 1

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
